apiVersion: v1
kind: Service
metadata:
  name: disco-pod
spec:
  selector:
    app: disco-pod
  type: NodePort
  ports:
    - port: 3000
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: disco-pod
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["endpoints"]
    verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: disco-pod
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: disco-pod
  namespace: default
roleRef:
  kind: Role
  name: disco-pod
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: disco-pod
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: disco-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: disco-pod
  template:
    metadata:
      labels:
        app: disco-pod
    spec:
      serviceAccountName: disco-pod
      containers:
        - name: my-service
        - name: disco-pod
          image: disco-pod
          imagePullPolicy: Never
          tty: true
          env:
            - name: DEBUG
              value: disco-pod*
